ame: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
      - ".github/workflows/client.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add client remote origin
        run: git remote add heroku-teater-client https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_CLIENT_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-teater-client `git subtree split --prefix client master`:refs/heads/master --force